### ISSUE TITLE
您好 有个关于融云 flutter 安卓远程推送问题 需要您指导一下

### ISSUE THREAD

**Issue by AlanJN** [leielyq/Flutter_leielyq_plugin#1]
您好 有个关于融云 flutter 安卓远程推送问题 需要您指导一下

**Comment by leielyq** [comment]
咋了发自我的iPhone------------------ 原始邮件 ------------------发件人: notifications@github.com <notifications@github.com>发送时间: 2020年9月17日 17:26收件人: leielyq/Flutter_leielyq_plugin <Flutter_leielyq_plugin@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[leielyq/Flutter_leielyq_plugin] 您好 有个关于融云 flutter 安卓远程推送问题 需要您指导一下 (#1)
您好 有个关于融云 flutter 安卓远程推送问题 需要您指导一下

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/leielyq/Flutter_leielyq_plugin/issues/1",
"url": "https://github.com/leielyq/Flutter_leielyq_plugin/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
